baseURL = 'https://luzekka.github.io/'
languageCode = 'zh-cn'
title = 'My New Hugo Site'
theme = 'terminal'

[menu]

  [[menu.main]]
    name = "Skills"
    url = "/skills/"
    weight = 1

  [[menu.main]]
    name = "作品集"
    url = "/作品集/"
    weight = 2

